# """
# ZHOPINGO MED - PATIENT NODE ROUTES v1.0
# Path: routes/patient_api.py
# Description: High-frequency telemetry ingestion, Patient UI sync, Emergency CDSS polling, Call Signaling & PDF Downloads.
# """

# from flask import Blueprint, request, jsonify, abort, send_file
# from datetime import datetime
# import uuid
# import logging
# from reportlab.pdfgen import canvas
# from reportlab.lib.pagesizes import letter
# from io import BytesIO

# # Import database and AI engine from your central files
# from database import db 
# from services.ai_engine import ClinicalIntelligenceMatrix

# logger = logging.getLogger("ZHOPINGO_PATIENT_API")
# patient_bp = Blueprint('patient_bp', __name__)

# # ==============================================================================
# # 1. HARDWARE TELEMETRY INGESTION (ESP32 / SENSORS)
# # ==============================================================================
# @patient_bp.route('/telemetry/ingest', methods=['POST'])
# def ingest_hardware_data():
#     """
#     INDUSTRIAL INGESTION ENDPOINT:
#     Receives high-frequency raw data from ESP32/Sensors, processes it through 
#     the AI Matrix, and determines the real-time risk profile.
#     """
#     try:
#         data = request.json
#         p_id = data.get('node_id')
        
#         if p_id not in db.patients:
#             logger.warning(f"Telemetry rejected: Unauthorized Node ID {p_id}")
#             return jsonify({"error": "UNAUTHORIZED_NODE", "code": "TEL_401"}), 401

#         p = db.patients[p_id]
        
#         # Raw Data Extraction (Fallback to averages if hardware fails)
#         raw_temp = float(data.get('temp', p.get('biometric_averages', {}).get('temp', 36.5)))
#         raw_hr = float(data.get('hr', p.get('biometric_averages', {}).get('hr', 75)))
#         raw_accel = float(data.get('accel', 1.0))

#         # 1. Pass through AI Clinical Intelligence Matrix
#         ai_analysis = ClinicalIntelligenceMatrix.process_telemetry(
#             p_id, raw_temp, raw_hr, raw_accel, p['age'], p['history']
#         )
        
#         # 2. Update Patient Cache
#         p['ai_advisor_cache'] = ai_analysis
#         p['risk_profile'] = ai_analysis['risk_profile']
        
#         # 3. Create Telemetry Payload
#         telemetry_entry = {
#             "time": datetime.now().isoformat(),
#             "temp": raw_temp,
#             "hr": raw_hr,
#             "accel": raw_accel,
#             "risk": ai_analysis['risk_profile']
#         }
        
#         # 4. Append to Vault & Manage Buffer (Max 10000 records per patient)
#         p['vitals_history'].append(telemetry_entry)
#         if len(p['vitals_history']) > 10000:
#             p['vitals_history'].pop(0)

#         # 5. Global Audit for Legal Compliance
#         if ai_analysis['risk_profile'] == "CRITICAL":
#             db.audit_log.append({
#                 "timestamp": telemetry_entry['time'],
#                 "node": p_id,
#                 "event": "CRITICAL_BIOMETRIC_BREACH",
#                 "severity_score": ai_analysis.get('severity_score', 100)
#             })

#         # 6. Response Command to Hardware (e.g., Turn on local buzzer)
#         hw_command = "TRIGGER_ALARM" if ai_analysis['risk_profile'] == "CRITICAL" else "STANDBY"
        
#         return jsonify({
#             "status": "SYNC_SUCCESS",
#             "risk_profile": ai_analysis['risk_profile'],
#             "hardware_command": hw_command
#         })

#     except Exception as e:
#         logger.error(f"Telemetry Ingestion Fault: {str(e)}")
#         return jsonify({"error": "INGESTION_FAULT", "details": str(e)}), 500

# # ==============================================================================
# # 2. SECURE BIOMETRIC HANDSHAKE (LOGIN)
# # ==============================================================================
# @patient_bp.route('/auth/handshake', methods=['POST'])
# def verify_patient_node():
#     """Authenticates the Patient UI using the Node ID generated by the Physician."""
#     data = request.json
#     p_id = data.get('node_id')
    
#     if p_id in db.patients:
#         p = db.patients[p_id]
#         logger.info(f"Secure Handshake Established for Node: {p_id}")
#         return jsonify({
#             "status": "AUTHORIZED",
#             "patient_name": p['name'],
#             "protocol": p['history'],
#             "session_token": p.get('security_hash', 'token_xyz')
#         })
        
#     return jsonify({"error": "NODE_NOT_FOUND", "code": "AUTH_404"}), 404

# # ==============================================================================
# # 3. CLINICAL DECISION SUPPORT SYSTEM (CDSS) - EMERGENCY POLLING
# # ==============================================================================
# @patient_bp.route('/rescue/cdss-status', methods=['GET'])
# def get_emergency_protocols():
#     """
#     Polled by the Patient UI. If risk is CRITICAL, this returns 
#     the Immediate First-Aid steps and Ambulance ETA.
#     """
#     p_id = request.args.get('node_id')
#     if p_id not in db.patients: return abort(404, "Invalid Node")
    
#     p = db.patients[p_id]
    
#     if p['risk_profile'] == "CRITICAL":
#         # Extract 'CRITICAL' and 'ACTION' tags from AI Cache
#         ai_cache = p.get('ai_advisor_cache', {})
#         critical_steps = []
        
#         # Handle dict format returning from newer AI Engine
#         if isinstance(ai_cache, dict):
#             critical_steps.extend(ai_cache.get('warning', []))
#             critical_steps.extend(ai_cache.get('action', []))
#         # Handle list format from older AI Engine
#         elif isinstance(ai_cache, list):
#             for instruction in ai_cache:
#                 if isinstance(instruction, dict) and instruction.get('type') in ['CRITICAL', 'ACTION', 'EMERGENCY']:
#                     critical_steps.append(instruction.get('msg', ''))
        
#         # Fallback instructions if AI processing delayed
#         if not critical_steps:
#             critical_steps = ["Maintain airway", "Do not move abruptly", "Wait for emergency unit"]

#         return jsonify({
#             "status": "CRITICAL_OVERRIDE_ACTIVE",
#             "ambulance_eta": "06:42 MIN", # In production, integrate Google Maps API here
#             "first_aid_steps": critical_steps,
#             "physician_on_call": "Dr. Peer Mohammed"
#         })
        
#     return jsonify({"status": "MONITORING_STABLE"})

# # ==============================================================================
# # 4. PATIENT VAULT (PRESCRIPTIONS, CHAT & NOTIFICATIONS)
# # ==============================================================================
# @patient_bp.route('/vault/sync', methods=['GET'])
# def get_patient_vault():
#     """Retrieves all historical data, chats, and prescriptions for the Patient UI."""
#     p_id = request.args.get('node_id')
#     if p_id not in db.patients: return abort(404, "Invalid Node")
    
#     p = db.patients[p_id]
#     return jsonify({
#         "chat_history": p['chat_vault'][-50:], # Last 50 messages
#         "prescriptions": p['prescription_vault'],
#         "active_notifications": p['notification_hub']
#     })

# @patient_bp.route('/chat/send', methods=['POST'])
# def send_patient_message():
#     """Handles patient sending messages to the physician."""
#     data = request.json
#     p_id = data.get('node_id')
#     text = data.get('message')
    
#     if p_id not in db.patients: return abort(404, "Invalid Node")
#     if not text: return abort(400, "Message cannot be empty")
    
#     msg_obj = {
#         "time": datetime.now().strftime("%H:%M"),
#         "sender": "Patient",
#         "text": text
#     }
#     db.patients[p_id]['chat_vault'].append(msg_obj)
    
#     # Notify Doctor (Optional depending on your UI logic)
#     if 'pending_queue' in db.doctors[db.patients[p_id]['doctor_id']]:
#         db.doctors[db.patients[p_id]['doctor_id']]['pending_queue'].append(f"NEW_MSG_{p_id}")
    
#     return jsonify({"status": "MESSAGE_DELIVERED"})

# @patient_bp.route('/clear-notifs', methods=['POST'])
# def clear_patient_notifs():
#     """Clears notifications once viewed in Patient UI."""
#     p_id = request.json.get('p_id')
#     if p_id in db.patients:
#         db.patients[p_id]['notification_hub'] = []
#         return jsonify({"status": "CLEARED"})
#     return jsonify({"error": "NOT_FOUND"}), 404

# # ==============================================================================
# # 5. PATIENT PDF DOWNLOAD (GET ROUTE)
# # ==============================================================================
# @patient_bp.route('/prescription/download', methods=['GET'])
# def download_patient_rx():
#     """Builds and serves the PDF file directly to the patient's browser."""
#     pid = request.args.get('node_id')
#     p = db.patients.get(pid)
#     if not p: return abort(404, "Patient not found")

#     buffer = BytesIO()
#     pdf = canvas.Canvas(buffer, pagesize=letter)
#     pdf.setFont("Helvetica-Bold", 24)
#     pdf.drawString(50, 750, "ZHOPINGO MED - CLINICAL Rx")
    
#     pdf.setFont("Helvetica", 12)
#     pdf.drawString(50, 725, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
#     pdf.line(50, 715, 550, 715)
    
#     pdf.drawString(50, 690, f"PATIENT IDENTITY: {p['name']} | NODE: {pid}")
#     pdf.drawString(50, 670, f"DIAGNOSIS: {p['history']}")
    
#     pdf.setFont("Helvetica-Bold", 14)
#     pdf.drawString(50, 630, "PRESCRIBED CARE PLAN:")
    
#     pdf.setFont("Helvetica", 12)
#     y_pos = 610
    
#     # Get the latest prescription from the vault
#     latest_rx = p['prescription_vault'][-1]['meds'] if p['prescription_vault'] else "No prescriptions found. Please consult physician."
    
#     # Handle multi-line strings
#     for line in latest_rx.split('\n'):
#         if line.strip(): # Skip empty lines
#             pdf.drawString(70, y_pos, f"• {line.strip()}")
#             y_pos -= 20
        
#     pdf.save()
#     buffer.seek(0)
    
#     return send_file(
#         buffer, 
#         as_attachment=True, 
#         download_name=f"Zhopingo_Rx_{pid}.pdf", 
#         mimetype='application/pdf'
#     )

# # ==============================================================================
# # 6. REGISTER NODE (ONBOARDING)
# # ==============================================================================
# @patient_bp.route('/register', methods=['POST'])
# def register_clinical_node():
#     """Validates and registers a new patient node."""
#     data = request.json
#     if not data or not data.get('name') or not data.get('age'):
#         return jsonify({"error": "Missing required fields", "code": "VAL_001"}), 400
        
#     pid = "P-" + str(uuid.uuid4())[:4].upper()
#     is_doc = data.get('created_by') == 'D001'
    
#     db.patients[pid] = {
#         "id": pid, "name": data.get('name'), "age": int(data.get('age')),
#         "history": data.get('history', 'Standard Observation'), 
#         "status": "ACCEPTED" if is_doc else "PENDING",
#         "doctor_id": "D001" if is_doc else None, 
#         "vitals_history": [],
#         "risk_profile": "NORMAL", 
#         "chat_vault": [], 
#         "notification_hub": [],
#         "prescription_vault": [], 
#         "ai_advisor_cache": {}, 
#         "thresholds": {"temp": 37.5, "accel": 2.8},
#         "security_hash": str(uuid.uuid4())
#     }
    
#     if is_doc: 
#         db.doctors["D001"]['active_patients'].append(pid)
#     else: 
#         db.doctors["D001"]['pending_queue'].append(pid)
    
#     return jsonify({"p_id": pid, "status": "SUCCESS", "auto_link": is_doc})


"""
ZHOPINGO MED - PATIENT NODE ROUTES v1.0
Path: routes/patient_api.py
Description: High-frequency telemetry ingestion, Patient UI sync, Emergency CDSS polling, Call Signaling & PDF Downloads.
"""

from flask import Blueprint, request, jsonify, abort, send_file
from datetime import datetime
import uuid
import logging
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from io import BytesIO

# Import database and AI engine from your central files
from database import db 
from services.ai_engine import ClinicalIntelligenceMatrix

logger = logging.getLogger("ZHOPINGO_PATIENT_API")
patient_bp = Blueprint('patient_bp', __name__)

# ==============================================================================
# 1. HARDWARE TELEMETRY INGESTION (ESP32 / SENSORS)
# ==============================================================================
@patient_bp.route('/telemetry/ingest', methods=['POST'])
def ingest_hardware_data():
    """
    INDUSTRIAL INGESTION ENDPOINT:
    Receives high-frequency raw data from ESP32/Sensors, processes it through 
    the AI Matrix, and determines the real-time risk profile.
    """
    try:
        data = request.json
        p_id = data.get('node_id')
        
        if p_id not in db.patients:
            logger.warning(f"Telemetry rejected: Unauthorized Node ID {p_id}")
            return jsonify({"error": "UNAUTHORIZED_NODE", "code": "TEL_401"}), 401

        p = db.patients[p_id]
        
        # Raw Data Extraction (Fallback to averages if hardware fails)
        raw_temp = float(data.get('temp', p.get('biometric_averages', {}).get('temp', 36.5)))
        raw_hr = float(data.get('hr', p.get('biometric_averages', {}).get('hr', 75)))
        raw_accel = float(data.get('accel', 1.0))

        # 1. Pass through AI Clinical Intelligence Matrix
        ai_analysis = ClinicalIntelligenceMatrix.process_telemetry(
            p_id, raw_temp, raw_hr, raw_accel, p['age'], p['history']
        )
        
        # 2. Update Patient Cache
        p['ai_advisor_cache'] = ai_analysis
        p['risk_profile'] = ai_analysis['risk_profile']
        
        # 3. Create Telemetry Payload
        telemetry_entry = {
            "time": datetime.now().isoformat(),
            "temp": raw_temp,
            "hr": raw_hr,
            "accel": raw_accel,
            "risk": ai_analysis['risk_profile']
        }
        
        # 4. Append to Vault & Manage Buffer (Max 10000 records per patient)
        p['vitals_history'].append(telemetry_entry)
        if len(p['vitals_history']) > 10000:
            p['vitals_history'].pop(0)

        # 5. Global Audit for Legal Compliance
        if ai_analysis['risk_profile'] == "CRITICAL":
            db.audit_log.append({
                "timestamp": telemetry_entry['time'],
                "node": p_id,
                "event": "CRITICAL_BIOMETRIC_BREACH",
                "severity_score": ai_analysis.get('severity_score', 100)
            })

        # 6. Response Command to Hardware (e.g., Turn on local buzzer)
        hw_command = "TRIGGER_ALARM" if ai_analysis['risk_profile'] == "CRITICAL" else "STANDBY"
        
        return jsonify({
            "status": "SYNC_SUCCESS",
            "risk_profile": ai_analysis['risk_profile'],
            "hardware_command": hw_command
        })

    except Exception as e:
        logger.error(f"Telemetry Ingestion Fault: {str(e)}")
        return jsonify({"error": "INGESTION_FAULT", "details": str(e)}), 500

# ==============================================================================
# 2. SECURE BIOMETRIC HANDSHAKE (LOGIN)
# ==============================================================================
@patient_bp.route('/auth/handshake', methods=['POST'])
def verify_patient_node():
    """Authenticates the Patient UI using the Node ID generated by the Physician."""
    data = request.json
    p_id = data.get('node_id')
    
    if p_id in db.patients:
        p = db.patients[p_id]
        logger.info(f"Secure Handshake Established for Node: {p_id}")
        return jsonify({
            "status": "AUTHORIZED",
            "patient_name": p['name'],
            "protocol": p['history'],
            "session_token": p.get('security_hash', 'token_xyz')
        })
        
    return jsonify({"error": "NODE_NOT_FOUND", "code": "AUTH_404"}), 404

# ==============================================================================
# 3. CLINICAL DECISION SUPPORT SYSTEM (CDSS) - EMERGENCY POLLING
# ==============================================================================
@patient_bp.route('/rescue/cdss-status', methods=['GET'])
def get_emergency_protocols():
    """
    Polled by the Patient UI. If risk is CRITICAL, this returns 
    the Immediate First-Aid steps and Ambulance ETA.
    """
    p_id = request.args.get('node_id')
    if p_id not in db.patients: return abort(404, "Invalid Node")
    
    p = db.patients[p_id]
    
    if p['risk_profile'] == "CRITICAL":
        # Extract 'CRITICAL' and 'ACTION' tags from AI Cache
        ai_cache = p.get('ai_advisor_cache', {})
        critical_steps = []
        
        # Handle dict format returning from newer AI Engine
        if isinstance(ai_cache, dict):
            critical_steps.extend(ai_cache.get('warning', []))
            critical_steps.extend(ai_cache.get('action', []))
        # Handle list format from older AI Engine
        elif isinstance(ai_cache, list):
            for instruction in ai_cache:
                if isinstance(instruction, dict) and instruction.get('type') in ['CRITICAL', 'ACTION', 'EMERGENCY']:
                    critical_steps.append(instruction.get('msg', ''))
        
        # Fallback instructions if AI processing delayed
        if not critical_steps:
            critical_steps = ["Maintain airway", "Do not move abruptly", "Wait for emergency unit"]

        return jsonify({
            "status": "CRITICAL_OVERRIDE_ACTIVE",
            "ambulance_eta": "06:42 MIN", # In production, integrate Google Maps API here
            "first_aid_steps": critical_steps,
            "physician_on_call": "Dr. Peer Mohammed"
        })
        
    return jsonify({"status": "MONITORING_STABLE"})

# ==============================================================================
# 4. PATIENT VAULT (PRESCRIPTIONS, CHAT & NOTIFICATIONS)
# ==============================================================================
@patient_bp.route('/vault/sync', methods=['GET'])
def get_patient_vault():
    """Retrieves all historical data, chats, and prescriptions for the Patient UI."""
    p_id = request.args.get('node_id')
    if p_id not in db.patients: return abort(404, "Invalid Node")
    
    p = db.patients[p_id]
    return jsonify({
        "chat_history": p['chat_vault'][-50:], # Last 50 messages
        "prescriptions": p['prescription_vault'],
        "active_notifications": p['notification_hub']
    })

@patient_bp.route('/chat/send', methods=['POST'])
def send_patient_message():
    """Handles patient sending messages to the physician."""
    data = request.json
    p_id = data.get('node_id')
    text = data.get('message')
    
    if p_id not in db.patients: return abort(404, "Invalid Node")
    if not text: return abort(400, "Message cannot be empty")
    
    msg_obj = {
        "time": datetime.now().strftime("%H:%M"),
        "sender": "Patient",
        "text": text
    }
    db.patients[p_id]['chat_vault'].append(msg_obj)
    
    # Notify Doctor (Optional depending on your UI logic)
    if 'pending_queue' in db.doctors[db.patients[p_id]['doctor_id']]:
        db.doctors[db.patients[p_id]['doctor_id']]['pending_queue'].append(f"NEW_MSG_{p_id}")
    
    return jsonify({"status": "MESSAGE_DELIVERED"})

@patient_bp.route('/clear-notifs', methods=['POST'])
def clear_patient_notifs():
    """Clears notifications once viewed in Patient UI."""
    p_id = request.json.get('p_id')
    if p_id in db.patients:
        db.patients[p_id]['notification_hub'] = []
        return jsonify({"status": "CLEARED"})
    return jsonify({"error": "NOT_FOUND"}), 404

# ==============================================================================
# 5. PATIENT PDF DOWNLOAD (GET ROUTE)
# ==============================================================================
@patient_bp.route('/prescription/download', methods=['GET'])
def download_patient_rx():
    """Builds and serves the PDF file directly to the patient's browser."""
    pid = request.args.get('node_id')
    p = db.patients.get(pid)
    if not p: return abort(404, "Patient not found")

    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(50, 750, "ZHOPINGO MED - CLINICAL Rx")
    
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, 725, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    pdf.line(50, 715, 550, 715)
    
    pdf.drawString(50, 690, f"PATIENT IDENTITY: {p['name']} | NODE: {pid}")
    pdf.drawString(50, 670, f"DIAGNOSIS: {p['history']}")
    
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, 630, "PRESCRIBED CARE PLAN:")
    
    pdf.setFont("Helvetica", 12)
    y_pos = 610
    
    # Get the latest prescription from the vault
    latest_rx = p['prescription_vault'][-1]['meds'] if p['prescription_vault'] else "No prescriptions found. Please consult physician."
    
    # Handle multi-line strings
    for line in latest_rx.split('\n'):
        if line.strip(): # Skip empty lines
            pdf.drawString(70, y_pos, f"• {line.strip()}")
            y_pos -= 20
        
    pdf.save()
    buffer.seek(0)
    
    return send_file(
        buffer, 
        as_attachment=True, 
        download_name=f"Zhopingo_Rx_{pid}.pdf", 
        mimetype='application/pdf'
    )

# ==============================================================================
# 6. REGISTER NODE (ONBOARDING)
# ==============================================================================
@patient_bp.route('/register', methods=['POST'])
def register_clinical_node():
    """Validates and registers a new patient node."""
    data = request.json
    if not data or not data.get('name') or not data.get('age'):
        return jsonify({"error": "Missing required fields", "code": "VAL_001"}), 400
        
    pid = "P-" + str(uuid.uuid4())[:4].upper()
    is_doc = data.get('created_by') == 'D001'
    
    db.patients[pid] = {
        "id": pid, "name": data.get('name'), "age": int(data.get('age')),
        "history": data.get('history', 'Standard Observation'), 
        "status": "ACCEPTED" if is_doc else "PENDING",
        "doctor_id": "D001" if is_doc else None, 
        "vitals_history": [],
        "risk_profile": "NORMAL", 
        "chat_vault": [], 
        "notification_hub": [],
        "prescription_vault": [], 
        "ai_advisor_cache": {}, 
        "thresholds": {"temp": 37.5, "accel": 2.8},
        "security_hash": str(uuid.uuid4())
    }
    
    if is_doc: 
        db.doctors["D001"]['active_patients'].append(pid)
    else: 
        db.doctors["D001"]['pending_queue'].append(pid)
    
    return jsonify({"p_id": pid, "status": "SUCCESS", "auto_link": is_doc})